services:
  app:
    build: .
    container_name: gekko_api
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "7508:7508"
    environment:
      PYTHONUNBUFFERED: "1"
      TZ: America/Mexico_City
    restart: always
    command: python ./src/server.py
